### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_character'

### ISSUE THREAD

**Issue by kasmith11** [TeamFightingICE/pyftg#1]
`non_delay_frame_data` is returning `None` which causes issues when trying to access character information via  `non_delay_frame_data.get_character()`.  Pictured below is my "AI" which I am running using a modified version of `Main_PyAIvsPyAI.py` from you all's python examples repository. The main area of focus being the line `print(non_delay_frame_data.get_character(self.player).hp)` which seeks to return hp data.

![image](https://user-images.githubusercontent.com/29484286/235380203-00e0f71c-3b79-4074-9326-3763cf243b98.png)

**Comment by kasmith11** [comment]
I am also making sure to boot DareFightingICE with the option  `--non-delay 0` to ensure that non-delay frame data is returned for both characters. Any ideas? Thanks

**Comment by yan-2** [comment]
How did you fix this? Same error happened to me.

**Comment by kasmith11** [comment]
Hello, @yan-2. If I remember correctly, I was making the mistake of using `--non-delay 0` as a command line argument instead of adding `--non-delay 0` to the `.sh` file that boots DareFightingICE.
